#!/bin/bash

# 
# The MIT License (MIT)
# 
# Copyright (c) 2016 khtdr.com@gmail.com
# 
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
# 


function usage {
  echo "pageboy-v1.2.2"
  echo "    $target            # runs as pageboy script"
  echo "    $target -r <page>  # runs requested page"
  echo "    $target -p <page>  # prints requested page"
  echo "    $target -c         # compiles to bash script"
  echo "    $target -d         # dumps page table"
  echo "    $target -h         # shows this message"
  echo "https://github.com/khtdr/pageboy"
  exit 0
}
read -r -a ARGV <<< "$@"
while (("$OPTIND" <= "$#")); do
  while getopts "dr:p:ch" opt; do
    case "$opt" in
      r) fn=run; page="$OPTARG" ;;
      p) fn=print; page="$OPTARG" ;;
      c) fn=compile ;;
      d) fn=dump; ;;
      *) fn=usage ;;
    esac
  done
  target=${target:-${ARGV[($OPTIND-1)]}}
  OPTIND=$(($OPTIND+1))
done
target=${target:-$0}
fn=${fn:-run}; page=${page:-pageboy}
if [[ $# = 0 ]] && [[ $0 =~ pageboy(-test)?$ ]]; then fn=usage; fi
[[ "$fn" != "usage" ]] || { usage; }
[[ -f "$target" ]] || {
  echo "no readable file name supplied"; usage;
}
read -r -d '' awkScript <<'EOF'
function record (end) {
  if (count == 0 && name ~ /bash/) { return }
  shebang=name
  if (shebang ~ /pageboy/) { shebang="/usr/bin/env bash" }
  count+=1
  print tag(name)(++tot[tag(name)])" NR>="(start+1)"&&"end">=NR "shebang
}
function tag (name) {
 split(name,words); bin=words[1];
 if (bin == "/usr/bin/env") { bin=words[2] }
 split(bin,path,"/"); return path[length(path)];
}
BEGIN { name=""; start=0; count=0 }
END { record(NR); }
/^#!/ {
  if (start != 0) { record(NR-1); }
  name=substr($0, 3); start=NR;
}
EOF
table="$(awk "$awkScript" $target)"
read -r -a spec <<< $(echo "$table" | grep ^$page | head -1);
name=${spec[0]}; spec[0]="";
range=${spec[1]}; spec[1]="";
shebang="${spec[@]}";
program=$(awk $range  $target);
case "$fn" in
  "print") echo "$program"; exit 0 ;;
  "dump") echo "$table"; exit 0 ;;
  "run") echo "$program" | PAGEBOY="$target" PAGE="$PAGEBOY -r" $shebang; exit $? ;;
esac
cat <(grep -v compile "$0") "$1"
exit 0
