#!/usr/bin/env bash

# 
# The MIT License (MIT)
# 
# Copyright (c) 2016 khtdr.com@gmail.com
# 
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
# 


# The usage function gets called when an unknown option is supplied.
# It prints out the usage example, and exits successfully.
function usage {
  echo "pageboy-v2.1.4"
  echo "    $target            # runs as pageboy script"
  echo "    $target -r <page>  # runs requested page"
  echo "    $target -p <page>  # prints requested page"
  echo "    $target -c         # compiles to bash script"
  echo "    $target -d         # dumps page table"
  echo "    $target -h         # shows this message"
  echo "https://github.com/khtdr/pageboy"
  exit 0
}

# This is where the script gets started. bash wants the
# usage function to be defined already, so it is up there.
read -r -a ARGV <<< "$@"
while (("$OPTIND" <= "$#")); do
  while getopts "dr:p:ch" opt; do
    case "$opt" in
      r) fn=run;
         page="$OPTARG";
         ARGV[(OPTIND-2)]="";
         ARGV[(OPTIND-3)]="";
         ;;
      p) fn=print;
         page="$OPTARG";
         ARGV[(OPTIND-2)]="";
         ARGV[(OPTIND-3)]="";
         ;;
      c) fn=compile; # comments trigger removal
         ARGV[(OPTIND-2)]=""; # compile
         ;; # compile
      d) fn=dump;
         ARGV[(OPTIND-2)]="";
         ;;
      *) fn=usage;
         ARGV[(OPTIND-2)]="";
         ;;
    esac
  done
  if [ -z "$target" ]; then
    if echo "$0" | grep "pageboy\(-test\)\?\$" &>/dev/null; then
      # the `read` commmand does not properly respect
      # the quoted filename with spaces. This splits it _again_
      # and removes all the parts from the ARGV array
      target=$1;
      read -r -a name_parts <<< "$target"
      parts_length=${#name_parts[@]}
      for i in $(seq "$parts_length"); do
        ARGV[(OPTIND-2+i)]=""
      done
    fi
  fi
  OPTIND=$((OPTIND+1))
done

# If the target was not explicitly passed in, refer to the name of the script
target=${target:-$0}

# If no command was given, then RUN is the command
fn=${fn:-run}

# If no page is given, pageboy is the page to use
page=${page:-pageboy}

if [[ $# = 0 ]] && [[ $0 =~ pageboy(-test)?$ ]]; then fn=usage; fi
[[ "$fn" != "usage" ]] || { usage; }
[[ -f "$target" ]] || {
  echo "<$target> is not a readable script"; usage;
}

# This embedded awk script is the heart of the program.
# It builds a look up table of all the pages which is
# used to extract substrings from the main script
# and evaluate them against their shebang.
read -r -d '' awkScript <<'EOF'
function record (end) {
  if (count == 0 && name ~ /bash/) { return }
  shebang=name
  if (shebang ~ /pageboy/) { shebang="/usr/bin/env bash" }
  count+=1
  split(shebang, sheparts, "#")
  print tag(name)(++tot[tag(name)])" NR>="(start+1)"&&"end">=NR "sheparts[1]
}
function tag (name) {
 split(name,words); bin=words[1];
 if (words[length(words)] ~ /^#/) {
   split(words[length(words)], comment, "#")
   return comment[2]
 }
 if (bin == "/usr/bin/env") { bin=words[2] }
 split(bin,path,"/"); return path[length(path)];
}
BEGIN { name=""; start=0; count=0 }
END { record(NR); }
/^#!/ {
  if (start != 0) { record(NR-1); }
  name=substr($0, 3); start=NR;
}
EOF
table="$(awk "$awkScript" "$target")"
read -r -a spec <<< "$(echo "$table" | grep ^"$page" | head -1)"
range=${spec[1]} # These are the indexes of the page
spec[0]=""
spec[1]=""
shebang="${spec[*]}"
program=$(awk "$range" "$target")
case "$fn" in
  "print") echo "$program"; exit 0 ;;
  "dump") echo "$table"; exit 0 ;;
  "run")
    if [[ $shebang =~ "env awk" ]]; then awk "$program"; exit $?; fi
    # Don't clobber the args for subshells, only use the args
    # provided by the external original command
    if [ -z "$PAGEBOY_ARGS" ]; then
      PAGEBOY_ARGS=$(echo ${ARGV[*]:-$PAGEBOY_ARGS} | xargs)
      # Must be exported to be availble to sub shell proccesses
      export PAGEBOY_ARGS
    fi
    echo "$program" | \
        PAGEBOY_ARGS="$PAGEBOY_ARGS" \
        PAGEBOY="$target" \
        PAGE="$target -r" \
        $shebang
    exit $?
    ;;
esac

# If the script got this far, it can only mean it was compiling to bash
# This removes the compile command and all comments
cat <(grep -v compile "$0" | grep -v '^#') "$1"
exit 0
